#!/bin/ksh

echo ""
echo "ds${indice}.JDBC_TYPE_ACTION=update"
echo "ds${indice}.JDBC_JNDI_APPLI=jdbc/"
#echo "ds${indice}.JDBC_ALIAS_USER="
#echo "ds${indice}.JDBC_ALIAS_PASS="
echo "ds${indice}.JDBC_URL="
echo ""
